# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: template.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etemplate.proto\x12\x12GRPCGlobalVariable\"\x07\n\x05\x45mpty\" \n\x04GInt\x12\x0b\n\x03idx\x18\x01 \x01(\x05\x12\x0b\n\x03val\x18\x02 \x01(\x05\"\x15\n\x06IntVal\x12\x0b\n\x03val\x18\x01 \x01(\x05\"!\n\x05GInts\x12\x0b\n\x03idx\x18\x01 \x01(\x05\x12\x0b\n\x03val\x18\x02 \x03(\x05\"\x16\n\x07IntVals\x12\x0b\n\x03val\x18\x01 \x03(\x05\"\'\n\x0cStringWithId\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03val\x18\x02 \x01(\t\"\x16\n\x08StringId\x12\n\n\x02id\x18\x01 \x01(\x05\"\"\n\x06GFloat\x12\x0b\n\x03idx\x18\x01 \x01(\x05\x12\x0b\n\x03val\x18\x02 \x01(\x02\"\x17\n\x08\x46loatVal\x12\x0b\n\x03val\x18\x01 \x01(\x02\"#\n\x07GFloats\x12\x0b\n\x03idx\x18\x01 \x01(\x05\x12\x0b\n\x03val\x18\x02 \x03(\x02\"\x18\n\tFloatVals\x12\x0b\n\x03val\x18\x01 \x03(\x02\x32\xe7\x05\n\x16GRPCGlobalVariableTask\x12?\n\x06SetInt\x12\x18.GRPCGlobalVariable.GInt\x1a\x19.GRPCGlobalVariable.Empty\"\x00\x12\x42\n\x06GetInt\x12\x1a.GRPCGlobalVariable.IntVal\x1a\x1a.GRPCGlobalVariable.IntVal\"\x00\x12\x41\n\x07SetInts\x12\x19.GRPCGlobalVariable.GInts\x1a\x19.GRPCGlobalVariable.Empty\"\x00\x12\x42\n\x07GetInts\x12\x18.GRPCGlobalVariable.GInt\x1a\x1b.GRPCGlobalVariable.IntVals\"\x00\x12P\n\x0fSetStringWithId\x12 .GRPCGlobalVariable.StringWithId\x1a\x19.GRPCGlobalVariable.Empty\"\x00\x12S\n\x0fGetStringWithId\x12\x1c.GRPCGlobalVariable.StringId\x1a .GRPCGlobalVariable.StringWithId\"\x00\x12\x43\n\x08SetFloat\x12\x1a.GRPCGlobalVariable.GFloat\x1a\x19.GRPCGlobalVariable.Empty\"\x00\x12\x46\n\x08GetFloat\x12\x1a.GRPCGlobalVariable.IntVal\x1a\x1c.GRPCGlobalVariable.FloatVal\"\x00\x12\x45\n\tSetFloats\x12\x1b.GRPCGlobalVariable.GFloats\x1a\x19.GRPCGlobalVariable.Empty\"\x00\x12\x46\n\tGetFloats\x12\x18.GRPCGlobalVariable.GInt\x1a\x1d.GRPCGlobalVariable.FloatVals\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'template_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=38
  _globals['_EMPTY']._serialized_end=45
  _globals['_GINT']._serialized_start=47
  _globals['_GINT']._serialized_end=79
  _globals['_INTVAL']._serialized_start=81
  _globals['_INTVAL']._serialized_end=102
  _globals['_GINTS']._serialized_start=104
  _globals['_GINTS']._serialized_end=137
  _globals['_INTVALS']._serialized_start=139
  _globals['_INTVALS']._serialized_end=161
  _globals['_STRINGWITHID']._serialized_start=163
  _globals['_STRINGWITHID']._serialized_end=202
  _globals['_STRINGID']._serialized_start=204
  _globals['_STRINGID']._serialized_end=226
  _globals['_GFLOAT']._serialized_start=228
  _globals['_GFLOAT']._serialized_end=262
  _globals['_FLOATVAL']._serialized_start=264
  _globals['_FLOATVAL']._serialized_end=287
  _globals['_GFLOATS']._serialized_start=289
  _globals['_GFLOATS']._serialized_end=324
  _globals['_FLOATVALS']._serialized_start=326
  _globals['_FLOATVALS']._serialized_end=350
  _globals['_GRPCGLOBALVARIABLETASK']._serialized_start=353
  _globals['_GRPCGLOBALVARIABLETASK']._serialized_end=1096
# @@protoc_insertion_point(module_scope)
