#!/bin/bash
### BEGIN INIT INFO
# Provides:          frying_fsm
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the frying_fsm service
# Description:       This script starts and stops the frying_fsm service.
### END INIT INFO

ServiceName=frying_fsm

status() {
    ps -ef | grep "/bin/bash /etc/${ServiceName}_script"
    tail -f /tmp/${ServiceName}.log
}

start() {
    echo "Starting ${ServiceName}_script service..."
    /usr/bin/screen -dmS $ServiceName bash -c "sudo /etc/${ServiceName}_script > /tmp/${ServiceName}.log 2>&1"
    echo "${ServiceName}_script service started."
}

stop() {
    ps -ef | grep "/bin/bash /etc/${ServiceName}_script" | awk '{print $2}' | sudo xargs kill -9
    echo "${ServiceName}_script service stopped."
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;

esac

exit 0

